<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: brjppru
 * Date: Fri, 27 Jan 2012 12:37:42 +0700
 */

$conf['title'] = 'Roman Y. Bogdanov';
$conf['start'] = 'root';
$conf['lang'] = 'ru';
$conf['template'] = 'sidebar';
$conf['tagline']    = '18+';  
$conf['license'] = '';
$conf['recent'] = 100;
$conf['youarehere'] = 1;
$conf['deaccent'] = '2';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['registernotify'] = 'sam@brj.pp.ru';
$conf['disableactions'] = 'register,resendpwd';
$conf['indexdelay'] = 0;
$conf['notify'] = 'sam@brj.pp.ru';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['canonical'] = 1;
$conf['mailfrom'] = 'sam@brj.pp.ru';
$conf['send404'] = 1;
$conf['sitemap'] = 1;
$conf['rss_type'] = 'rss2';
$conf['rss_linkto'] = 'current';
$conf['rss_content'] = 'htmldiff';
$conf['plugin']['tag']['pingtechnorati'] = 1;
$conf['plugin']['tag']['toolbar_icon'] = 1;
$conf['plugin']['tag']['list_tags_of_subns'] = 1;
$conf['plugin']['brj404']['idnamespace'] = 'brj:kuda';
$conf['openregister'] = '0';

// end auto-generated content
